version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  apt_packages:
    - pandoc

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
        - docs
        - examples
