name: felupe-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - meshio
  - matplotlib
  - panel
  - trame
  - pip
  - pip:
    - einsumt
    - tensortrax
    - matadi
    - pyvista
    - felupe