name: mybinder-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pip
  - pip:
    - einsumt
    - tensortrax
    - h5py
    - meshio
    - matadi
    - pyvista
    - felupe