name: Codecov

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run:
    name: Upload coverage report to codecov.io
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Test with tox
      run: |
        pip install tox
        tox -- --cov felupe --cov-report xml --cov-report term
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.python-version == '3.9' }}