name: Codecov

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run:
    name: Upload coverage report to codecov.io
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/checkout@v2
    - name: Test with tox
      run: |
        pip install tox
        tox -- --cov felupe --cov-report xml --cov-report term
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2